//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChronoMedic.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calls
    {
        public int Id { get; set; }
        public string NameCall { get; set; }
        public string LastNameCall { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Adress { get; set; }
        public string Description { get; set; }
    }
}
