//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChronoMedic.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarsData
    {
        public int Id { get; set; }
        public string NumberCar { get; set; }
        public string Status { get; set; }
        public string Phone { get; set; }
    }
}
